name: 멜론 티켓 빈자리 확인

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check_ticket:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # 1. 내 저장소에 있는 코드 파일들(check.js)을 가져옵니다.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js 실행 환경을 준비합니다.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. 필요한 라이브러리를 설치합니다.
      - name: Install Dependencies
        run: npm install axios querystring

      # 4. 우리가 만든 check.js 파일을 실행합니다.
      - name: Check Tickets & Notify
        env:
          # --- ★ 여기에 자신의 정보만 입력하세요! ★ ---
          PRODUCT_ID: "211664"
          SCHEDULE_ID: "100001"
          SEAT_IDS_JSON: '[{ "name": "VIP(스탠딩)", "id": "12285" }, { "name": "스탠딩 R", "id": "10674" }, { "name": "지정석 R", "id": "10062" }]'
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: node check.js
